name: Build RPM
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  FEDORAVERSION: 38

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:$FEDORAVERSION
      env:
        SPECFILE: "ddcci-driver-linux-kmod.spec"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          dnf in -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$FEDORAVERSION.noarch.rpm
          dnf in -y spectool mock mock-rpmfusion-free
          spectool -g $SPECFILE
          rpmbuild -bs $SPECFILE --define "_topdir ."  --define "_sourcedir ."  --define "_srcrpmdir ."
          mock -r fedora-$FEDORAVERSION-x86_64-rpmfusion_free -nN --rebuild *.src.rpm --resultdir .

