name: Build RPM
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  FEDORAVERSION: 38
  SPECFILE: "ddcci-driver-linux-kmod.spec"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
      options: --privileged
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          dnf in -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$FEDORAVERSION.noarch.rpm
          dnf in -y rpmdevtools 'dnf-command(builddep)'
          dnf builddep -y $SPECFILE
          spectool -g $SPECFILE
          rpmbuild -ba $SPECFILE --buildroot "$PWD"
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        if: success() || failure()
        with:
          name: RPM
          path: .

